In [1]:
import sys 
import numpy as np
import pandas as pd
print("Python:", sys.version)
print("Numpy:",np.__version__)
print("Pandas:", pd.__version__)

Python: 3.13.1 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 17:02:46) [MSC v.1929 64 bit (AMD64)]
Numpy: 2.5.1
Pandas: 2.3.3


In [2]:
a = 10
b = 3.14
name = "Python"
active = True
print(type(a))
print(type(b))
print(type(name))
print(type(active))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [3]:
numbers = [10, 20, 30]
point = (4, 5)
student = {"name": "An", "score": 8.5}
unique_values = {1, 2, 3, 3}
print(numbers)
print(point)
print(student)
print(unique_values)

[10, 20, 30]
(4, 5)
{'name': 'An', 'score': 8.5}
{1, 2, 3}


In [4]:
x = [10, 20, 30, 40, 50]
print(x[0])
print(x[-1])
print(x[1:4])
print(x[:3])
print(x[::2])

10
50
[20, 30, 40]
[10, 20, 30]
[10, 30, 50]


In [5]:
a = [1, 2, 3]
b = a
b[0] = 100
print(a)
print(b)

[100, 2, 3]
[100, 2, 3]


In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
#attribute
print(arr.shape) 
print(arr.ndim)
print(arr.dtype)
#method
print(arr.sum())
print(arr.mean())

(2, 3)
2
int64
21
3.5


In [7]:
np.array?
np.read_csv?

Object `np.read_csv` not found.


Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [8]:
%timeit sum(range(1000))
%timeit [x**2 for x in range(1000)]

28.4 μs ± 7.48 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
150 μs ± 18.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
%pwd
!dir

 Volume in drive C is OS
 Volume Serial Number is 7BFB-2E60

 Directory of C:\Hon\Nam_3_HK1 2026_2027\DataScience\Hoan-Data-Science-Course\notebooks

09/01/2026  03:02 PM    <DIR>          .
08/31/2026  10:24 PM    <DIR>          ..
09/01/2026  09:39 AM    <DIR>          .ipynb_checkpoints
09/01/2026  03:02 PM            31,726 on_tap_01_python_jupyter.ipynb
               1 File(s)         31,726 bytes
               3 Dir(s)  160,903,557,120 bytes free


In [10]:
numbers = [5, 10, 15, 20, 25]
result = [x**2 for x in numbers if x > 10]
print(result)


[225, 400, 625]


In [11]:
import numpy as np
numbers = [5, 10, 15, 20, 25]
arr = np.array(numbers)
print(arr)
print(type(arr))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>


In [12]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(5,)
5
int64


In [13]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[0])
print(arr[2])
print(arr[-1])

5
15
25


In [14]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[:3])
print(arr[1:4])
print(arr[::2])
print(arr[::-1])
#[start : stop : step] stop KHÔNG được lấy

[ 5 10 15]
[10 15 20]
[ 5 15 25]
[25 20 15 10  5]


In [15]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]])
print(matrix[:2, :2])
print(matrix[:, 0]) # : lấy tất cả, -> tất cả hàng cột 0


[[10 20]
 [40 50]]
[10 40 70]


In [16]:
arr = np.array([5, 10, 15, 20, 25])
mask = arr > 10
print(mask)
result = arr**2
print(result[arr>10])
print(result[mask])

[False False  True  True  True]
[225 400 625]
[225 400 625]


In [17]:
arr = np.array([5, 10, 15, 20, 25])
mask = arr > 10
print(mask)


[False False  True  True  True]


In [18]:
arr = np.array([5, 10, 15, 20, 25])
result = arr[arr>10]**2
print(result)

[225 400 625]


In [19]:
arr = np.array([5, 10, 15, 20, 25])
print(arr.sum()) # tong
print(arr.mean()) # trung binh
print(arr.min()) # nho nhat
print(arr.max()) # lon nhat
print(arr.std())

75
15.0
5
25
7.0710678118654755


In [20]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(x[1, 1:])
print(x[:, 1])
print(x[x > 50])

[50 60]
[20 50 80]
[60 70 80 90]


x[1, 1:]
  ↑  ↑
  │  └─ từ cột 1 trở đi
  └──── hàng 1

x[:, 1]
  ↑  ↑
  │  └─ cột 1
  └──── tất cả hàng

x[x > 50]
   ↑
boolean mask

In [21]:
x = np.array([10, 20, 30, 40, 50])
sub = x[1:4]
print("x =", x)
print("sub =", sub)
sub[0] = 999
print("x =", x)
print("sub =", sub)

x = [10 20 30 40 50]
sub = [20 30 40]
x = [ 10 999  30  40  50]
sub = [999  30  40]


In [22]:
x = np.array([10, 20, 30, 40, 50])
sub = x[1:4].copy()
sub[0] = 999
print('sub =', sub)
print('x =',x)

sub = [999  30  40]
x = [10 20 30 40 50]


In [23]:
x = np.arange(1,13)
print(x)
print(x.shape)
matrix = x.reshape(3,4)
print(matrix)
print(x.reshape(-1,2)) # Cho trước 2 cột, NumPy tự tính ra 6 hàng:
                        # shape: (6, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [24]:
x = np.arange(12)
a = x.reshape(3,-1)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [25]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) 
print(x.sum())
print(x.sum(axis=0))

21
[5 7 9]


axis=0
→ gộp theo chiều hàng
→ còn lại từng cột

In [26]:
print(x.sum(axis=1))

[ 6 15]


axis=1
→ gộp theo chiều cột
→ còn lại từng hàng

In [27]:
x = np.array([[10, 20, 30],
              [40, 50, 60]])
print(x.mean(axis=0))
print(x.mean(axis=1))

[25. 35. 45.]
[20. 50.]


In [28]:
print(x + 5)
print(x*2)
print(x**2)
print(np.sqrt(x))
print(np.exp(x))
print(np.log(x))

[[15 25 35]
 [45 55 65]]
[[ 20  40  60]
 [ 80 100 120]]
[[ 100  400  900]
 [1600 2500 3600]]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]


In [29]:
print(x+10)

[[20 30 40]
 [50 60 70]]


In [30]:
x = np.array([[1, 2, 3],
             [4, 5, 6]])
v = np.array([10, 20, 30])
print(x+v)

[[11 22 33]
 [14 25 36]]


In [31]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(x.sum(axis=0))
print(x.mean(axis=1))
print(x+100)
v = np.array([1, 2, 3])
print(x+v)

[120 150 180]
[20. 50. 80.]
[[110 120 130]
 [140 150 160]
 [170 180 190]]
[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [32]:
x = np.array([5, 10, 15, 20, 25, 30])
print(x>10)
print(x[(x>10) & (x<30)])

[False False  True  True  True  True]
[15 20 25]


In [33]:
print(x[(x < 10) | (x > 25)])

[ 5 30]


In [34]:
print(np.any(x>18))
print(np.all(x>0))
print(np.all(x>10))

True
True
False


any → có ÍT NHẤT một phần tử True?
all → TẤT CẢ có True không?

In [35]:
x = np.array([40, 10, 70, 20, 90])
print(x.max())     # max()     → GIÁ TRỊ lớn nhất -> value
print(x.argmax())  # argmax()  → VỊ TRÍ của giá trị lớn nhất -> index
print(x.min())
print(x.argmin())

90
4
10
1


In [36]:
print(np.sort(x))
print(x)

[10 20 40 70 90]
[40 10 70 20 90]


In [37]:
print(np.argsort(x))
idx = np.argsort(x)
print(x[idx])

[1 3 0 2 4]
[10 20 40 70 90]


In [38]:
print(x[[0,2,4]]) #Fancy Indexing

[40 70 90]


In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a, b])
print(c)
a = np.array([[1,2],
              [3,4]])
#2D
b = np.array([
    [5, 6]
])
print(np.vstack([a,b]))


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [40]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [10],
    [20]
])
print(np.hstack([a, b]))

[[ 1  2 10]
 [ 3  4 20]]


In [41]:
x = np.array([45, 80, 67, 92, 38, 75, 88])
print(x[(x>60) & (x<=80)])
print(np.any(x>90))
print(np.max(x))
print(np.argmax(x))
y = np.sort(x)
print(y[-1])
print(y)

[80 67 75]
True
92
3
92
[38 45 67 75 80 88 92]


In [43]:
import pandas as pd
scores = pd.Series([90, 85, 78, 92])

In [46]:
print(scores)
print(type(scores))

0    90
1    85
2    78
3    92
dtype: int64
<class 'pandas.core.series.Series'>


In [48]:
scores = pd.Series(
    [90, 85, 78, 92],
    index=['An', 'Binh', 'Chi', 'Dung'])
print(scores)

An      90
Binh    85
Chi     78
Dung    92
dtype: int64


In [50]:
print(scores.values)
print(scores.index)

[90 85 78 92]
Index(['An', 'Binh', 'Chi', 'Dung'], dtype='object')


In [51]:
print(scores['An'])
print(scores['Chi'])

90
78
